### ISSUE TITLE
De-serialization issue when following Quickstart steps

### ISSUE THREAD

**Issue by leondmello** [jsonapi-suite/jsonapi_suite#16] opened 2017-08-15 01:33 UTC
I'm trying to follow the steps outlined [here](https://jsonapi-suite.github.io/jsonapi_suite/quickstart)
Tried to create a simple resource using postman with the following request parameters
`Content-Type:application/vnd.api+json`
```
{
	"data": {
		"type": "stocks",
		"attributes": {
			"symbol": "AAPL"
		}
	}
}
```
The Rails server for some reason is adding a root element which is breaking the deserialization
```
Processing by StocksController#create as */*
  Parameters: {"_jsonapi"=>{"data"=>{"type"=>"stocks", "attributes"=>{"symbol"=>"AAPL"}}}}
ERROR: NoMethodError: undefined method `[]' for nil:NilClass
```

**Comment by leondmello** [comment] 2017-08-15 03:12
I'm thinking its [this line](https://github.com/jsonapi-rb/jsonapi-rails/blob/master/lib/jsonapi/rails/parser.rb#L7) that adds the top level key
Not sure how I would turn it off

**Comment by richmolj** [comment] 2017-08-15 14:59
@leondmello I cannot reproduce this when I follow the quickstart. Are you sure you followed all of the steps? The key prefix is expected.

**Comment by leondmello** [comment] 2017-08-16 01:54
[Here is a repository](https://github.com/leondmello/jsonapi_suite_quickstart) I created from scratch.
I ran all the steps[ in the black boxes u](https://jsonapi-suite.github.io/jsonapi_suite/quickstart)ntil Seeding data

**Comment by leondmello** [comment] 2017-08-18 02:58
@richmolj, did you get a chance to look at the example I posted?

**Comment by richmolj** [comment] 2017-08-18 13:21
Thanks @leondmello - you're correct, this was an issue with a downstream dependency being bumped. Fixed in the latest version of `jsonapi_compliable`, version `0.7.8`

**Closed by richmolj** 2017-08-18 13:21 UTC

**Comment by moveson** [comment] 2018-02-28 06:21
I'm getting the same response with an RSpec test, using the suggested template for a basic create:

```
require 'rails_helper'

RSpec.describe "courses#create", type: :request do
  subject(:make_request) { jsonapi_post "/api/v2/courses", payload }

  describe 'basic create' do
    let(:payload) do
      {
        data: {
          type: 'courses',
          attributes: {
            name: 'Test Course',
            description: 'A test course',
            nextStartTime: '2018-07-01 06:00:00'
          }
        }
      }
    end

    before { login_as_admin }

    it 'creates the resource' do
      expect { make_request }.to change { Course.count }.by(1)
      course = Course.last

      assert_payload(:course, course, json_item)
    end
  end
end
```
The test fails with:
```
NoMethodError: undefined method `[]' for nil:NilClass
./config/initializers/wrap_parameters.rb:17:in `process_action'
./spec/controllers/api/v2/courses/create_spec.rb:4:in `block (2 levels) in <main>'
./spec/controllers/api/v2/courses/create_spec.rb:23:in `block (4 levels) in <main>'
./spec/controllers/api/v2/courses/create_spec.rb:23:in `block (3 levels) in <main>'
-e:1:in `<main>'
```
